using System;
using System.IO;
using System.Linq;
using Xunit;

namespace ClimaSense.Web.Tests;

/// <summary>
/// Locks AC #7 — "No [JsonPropertyName] attributes appear in the
/// generated .NET DTOs (camelCase is the wire convention; codegen
/// handles it)."
///
/// The test walks `src/ClimaSense.Web/Generated/` and asserts that
/// no .cs file in that subtree mentions `[JsonPropertyName`. The
/// global JsonNamingPolicy.CamelCase set in `Program.cs` (incoming)
/// and on the MLServiceClient's JsonSerializerOptions (outgoing) is
/// the single source of truth for wire casing.
/// </summary>
public sealed class GeneratedClientHygieneTests
{
    private static string GeneratedTreeRoot()
    {
        // Walk up from the test assembly's AppContext.BaseDirectory.
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            var candidate = Path.Combine(
                dir.FullName, "src", "ClimaSense.Web", "Generated");
            if (Directory.Exists(candidate))
            {
                return candidate;
            }
            dir = dir.Parent;
        }
        throw new DirectoryNotFoundException(
            "Could not locate src/ClimaSense.Web/Generated by walking up from " +
            AppContext.BaseDirectory);
    }

    [Fact]
    public void No_JsonPropertyName_attributes_in_generated_tree()
    {
        var root = GeneratedTreeRoot();
        var offenders = Directory
            .EnumerateFiles(root, "*.cs", SearchOption.AllDirectories)
            .Where(path => File.ReadAllText(path).Contains("[JsonPropertyName"))
            .ToList();

        Assert.True(
            offenders.Count == 0,
            "Generated DTOs must not use [JsonPropertyName]; offenders:\n  - "
            + string.Join("\n  - ", offenders));
    }

    [Fact]
    public void Generated_DTOs_carry_the_autogenerated_banner()
    {
        var root = GeneratedTreeRoot();
        var modelFiles = Directory.EnumerateFiles(
            Path.Combine(root, "MLClient", "Models"), "*.cs");

        foreach (var f in modelFiles)
        {
            var firstLines = string.Join(
                "\n",
                File.ReadAllLines(f).Take(3));
            // Kiota emits `<auto-generated/>` (self-closing). We accept
            // both forms so a future hand-authored snapshot (`<auto-generated>...
            // </auto-generated>`) doesn't break the test.
            Assert.True(
                firstLines.Contains("<auto-generated/>", StringComparison.Ordinal)
                || firstLines.Contains("<auto-generated>", StringComparison.Ordinal),
                $"{f}: missing <auto-generated> banner in the first three lines.");
        }
    }
}
