"""ClimaSense.ML — generated DTO package.

`generated.py` is regenerated by `scripts/regen-contracts.sh` from
`contracts/openapi.yaml`. Treat it as read-only; hand-edits will be
clobbered on the next regen.
"""

from .generated import (  # noqa: F401  (re-export surface for handlers)
    AnomalyDetectRequest,
    AnomalyDetectResponse,
    AnomalyRow,
    AnomalyType,
    ComfortRating,
    ComfortScoreResponse,
    ComfortSeason,
    DayProfileRow,
    ForecastEnvelope,
    ForecastPoint,
    ForecastRequest,
    HealthStatus,
    LatestReading,
    ProblemDetails,
    ProfilesAnalyzeRequest,
    ProfilesAnalyzeResponse,
    Status as HealthStatusEnum,
)
