# === GENERATED — DO NOT EDIT BY HAND ===
# Regenerated by scripts/regen-contracts.sh from contracts/openapi.yaml.
# Pydantic v2 models. camelCase JSON aliases on the wire are produced
# by datamodel-code-generators --snake-case-field mode plus the
# emitted Field(..., alias=camelCase) annotations.

# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   version:   0.57.0

from __future__ import annotations

from datetime import date as date_aliased
from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Status(StrEnum):
    """
    Coarse-grained outcome of a health probe.
    """

    ok = "ok"
    degraded = "degraded"
    unavailable = "unavailable"


class Checks(StrEnum):
    """
    Per-dependency probe outcome.
    """

    ok = "ok"
    fail = "fail"
    skipped = "skipped"


class HealthStatus(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Status
    service: str = Field(
        ...,
        description="Logical name of the responding service (e.g. `web`, `ml`).",
        examples=["web"],
    )
    ts: AwareDatetime = Field(
        ..., description="Server timestamp at which the probe was answered."
    )
    checks: dict[str, Checks] | None = Field(
        None, description="Per-dependency probe outcomes (db, ml, etc.)."
    )


class LatestReading(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    reading_time: AwareDatetime = Field(
        ..., alias="readingTime", description="Timestamp of the latest reading (UTC)."
    )
    temperature_c: float = Field(
        ...,
        alias="temperatureC",
        description="Temperature in degrees Celsius.",
        examples=[21.5],
    )
    humidity_pct: float = Field(
        ...,
        alias="humidityPct",
        description="Relative humidity as a percentage (0–100).",
        examples=[47.0],
        ge=0.0,
        le=100.0,
    )


class RangeBucket(StrEnum):
    """
    Aggregation granularity for `/api/readings/range`.
      * `raw`  — un-aggregated rows (capped by `CLIMASENSE_RAW_MAX_DAYS`).
      * `hour` — `DATE_BUCKET(HOUR, 1, ReadingTime)`.
      * `day`  — `DATE_BUCKET(DAY, 1, ReadingTime)`.
      * `week` — `DATE_BUCKET(WEEK, 1, ReadingTime)`.

    """

    raw = "raw"
    hour = "hour"
    day = "day"
    week = "week"


class BucketedReading(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    bucket_time: AwareDatetime = Field(
        ...,
        alias="bucketTime",
        description="Bucket start (UTC). For `raw`, this is the row's `ReadingTime`;\nfor aggregated buckets, the `DATE_BUCKET` boundary.\n",
    )
    sample_count: int = Field(
        ...,
        alias="sampleCount",
        description="Count of `SensorReadings` rows that fell into the bucket.\n`0` for empty aggregated buckets (metric fields are then `null`).\n",
        ge=0,
    )
    temperature_mean: float | None = Field(
        None,
        alias="temperatureMean",
        description="Mean temperature (°C) over the bucket. `null` when\n`sampleCount` is 0. For `raw`, equals the row's temperature.\n",
    )
    temperature_min: float | None = Field(
        None,
        alias="temperatureMin",
        description="Min temperature (°C). `null` when `sampleCount` is 0.",
    )
    temperature_max: float | None = Field(
        None,
        alias="temperatureMax",
        description="Max temperature (°C). `null` when `sampleCount` is 0.",
    )
    humidity_mean: float | None = Field(
        None,
        alias="humidityMean",
        description="Mean humidity (% RH). `null` when `sampleCount` is 0.",
    )
    humidity_min: float | None = Field(
        None,
        alias="humidityMin",
        description="Min humidity. `null` when `sampleCount` is 0.",
    )
    humidity_max: float | None = Field(
        None,
        alias="humidityMax",
        description="Max humidity. `null` when `sampleCount` is 0.",
    )


class BucketedReadingsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    start: AwareDatetime = Field(
        ..., description="Echo of the requested window start (clipped at cursor)."
    )
    end: AwareDatetime = Field(
        ..., description="Echo of the requested window end (clipped at cursor)."
    )
    bucket: RangeBucket
    buckets: list[BucketedReading]


class HeatmapCell(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date: date_aliased = Field(
        ..., description="Calendar day (UTC, ISO 8601 `YYYY-MM-DD`)."
    )
    sample_count: int = Field(
        ...,
        alias="sampleCount",
        description="Count of readings on this day (0 if no data).",
        ge=0,
    )
    temperature_mean: float | None = Field(
        None,
        alias="temperatureMean",
        description="Daily mean temperature (°C). `null` when `sampleCount` is 0.\n",
    )


class HeatmapResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    year: int = Field(..., description="Echo of the requested year.", ge=1900, le=2100)
    cells: list[HeatmapCell] = Field(
        ...,
        description="One cell per calendar day in `year`. Length is 365 or 366\ndepending on leap-year status.\n",
    )


class ProblemDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    error: str = Field(
        ...,
        description="Machine-readable error slug (snake_case).",
        examples=["ml_service_unavailable"],
    )
    message: str = Field(
        ..., description="Human-readable explanation suitable for the browser."
    )
    request_id: str | None = Field(
        None,
        alias="requestId",
        description="Echo of the inbound `X-Request-ID` header for correlation.",
    )


class ForecastRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    horizon_hours: int = Field(
        ...,
        alias="horizonHours",
        description="Forecast horizon in hours (1–168).",
        examples=[72],
        ge=1,
        le=168,
    )


class ForecastPoint(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    target_time: AwareDatetime = Field(
        ..., alias="targetTime", description="Wall-clock time the prediction targets."
    )
    predicted_temperature: float = Field(
        ...,
        alias="predictedTemperature",
        description="Predicted air temperature in °C.",
    )
    predicted_humidity: float = Field(
        ..., alias="predictedHumidity", description="Predicted relative humidity in %."
    )
    confidence_lower_temp: float = Field(
        ...,
        alias="confidenceLowerTemp",
        description="Lower bound of the 95 % temperature CI.",
    )
    confidence_upper_temp: float = Field(
        ...,
        alias="confidenceUpperTemp",
        description="Upper bound of the 95 % temperature CI.",
    )


class ForecastEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    generated_at: AwareDatetime = Field(
        ...,
        alias="generatedAt",
        description="Cursor value at the moment the forecast was emitted.",
    )
    model_version: str = Field(
        ...,
        alias="modelVersion",
        description="Identifier of the boot-fitted lag-LR artefact.",
        examples=["lag-lr-v1"],
    )
    horizon_hours: int = Field(..., alias="horizonHours", ge=1, le=168)
    points: list[ForecastPoint]


class AnomalyType(StrEnum):
    """
    The detector that flagged a row. `sensor_failure` and
    `residual_outlier` are point-in-time; `regime_shift` is a
    90-day scan-and-replace.

    """

    sensor_failure = "sensor_failure"
    regime_shift = "regime_shift"
    residual_outlier = "residual_outlier"


class AnomalyDetectRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    types: list[AnomalyType] = Field(
        ..., description="Which detectors to run.", min_length=1
    )
    start_date: AwareDatetime | None = Field(
        None,
        alias="startDate",
        description="Window start (inclusive). Optional — defaults are detector-specific\n(24 h for point-in-time, 90 d for changepoint).\n",
    )
    end_date: AwareDatetime | None = Field(
        None,
        alias="endDate",
        description="Window end (inclusive). Optional — defaults to the cursor.",
    )


class AnomalyRow(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    anomaly_type: AnomalyType = Field(..., alias="anomalyType")
    reading_time: AwareDatetime = Field(..., alias="readingTime")
    severity: float = Field(
        ...,
        description="For `residual_outlier`: |residual| / rolling σ.\nFor the other detectors: 1.0 (binary).\n",
    )
    description: str | None = Field(
        None, description='Short free-text description (e.g. `"gap > 10 min"`).'
    )


class AnomalyRunSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sensor_failure: int = Field(
        ...,
        alias="sensorFailure",
        description="Newly-inserted `sensor_failure` rows in the 24h scan window.",
    )
    residual_outlier: int = Field(
        ...,
        alias="residualOutlier",
        description="Newly-inserted `residual_outlier` rows in the 24h scan window.",
    )
    regime_shift: int = Field(
        ...,
        alias="regimeShift",
        description="Post-replace `regime_shift` row count in the 90d scan window. Scan-and-replace means this is the row count *after* the transaction commits, not the net insert count.\n",
    )


class AnomalyDetectResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    inserted: int = Field(
        ...,
        description="Total count of new rows committed (idempotent — duplicates are 0). For `regime_shift` this is the post-replace row count (scan-and-replace produces a stable rowset, not net inserts).\n",
    )
    total_scanned: int = Field(
        ...,
        alias="totalScanned",
        description="Count of readings scanned by the detectors.",
    )
    per_type: AnomalyRunSummary = Field(..., alias="perType")
    rows: list[AnomalyRow]


class ProfilesAnalyzeRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    start_date: date_aliased = Field(
        ..., alias="startDate", description="Window start (UTC date, inclusive)."
    )
    end_date: date_aliased = Field(
        ..., alias="endDate", description="Window end (UTC date, inclusive)."
    )


class Pattern(StrEnum):
    """
    Derived `DayProfile` label. Precedence (per `init-db.sql.fn_classify_pattern`):
    `volatile > warm > cool > quiet`.

    """

    quiet = "quiet"
    warm = "warm"
    cool = "cool"
    volatile = "volatile"


class DayProfileRow(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date: date_aliased
    day_of_week: int = Field(
        ...,
        alias="dayOfWeek",
        description="0 = Monday, 6 = Sunday (ISO 8601 weekday).",
        ge=0,
        le=6,
    )
    mean_residual: float = Field(
        ...,
        alias="meanResidual",
        description="Mean of standardised residuals for the day.",
    )
    max_abs_zscore: float = Field(
        ..., alias="maxAbsZscore", description="Largest absolute z-score for the day."
    )
    pattern: Pattern


class ProfilesAnalyzeResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    rows_replaced: int = Field(
        ...,
        alias="rowsReplaced",
        description="Count of `DayProfiles` rows replaced in this run.",
    )
    rows: list[DayProfileRow]


class ComfortSeason(StrEnum):
    """
    Selected by calendar month + `COMFORT_HEMISPHERE` env var.
    """

    summer = "summer"
    winter = "winter"


class ComfortRating(StrEnum):
    """
    Qualitative bucket derived from `score`.
    """

    excellent = "excellent"
    acceptable = "acceptable"
    marginal = "marginal"
    uncomfortable = "uncomfortable"


class ComfortScoreResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    score: float = Field(
        ...,
        description="100 inside the ASHRAE 55 polygon for the selected season;\n`max(0, 100 - α · d_polygon)` outside.\n",
        ge=0.0,
        le=100.0,
    )
    rating: ComfortRating
    season: ComfortSeason
    bucket_time: AwareDatetime = Field(
        ..., alias="bucketTime", description="Cursor value the score was computed at."
    )
    average_temperature: float | None = Field(
        None,
        alias="averageTemperature",
        description="Mean of the trailing-window air temperature in °C.",
    )
    average_humidity: float | None = Field(
        None,
        alias="averageHumidity",
        description="Mean of the trailing-window relative humidity in %.",
    )


class Provenance(StrEnum):
    """
    Origin of a leaderboard row.
      * `notebook` — copied from `assets/results.json`.
      * `live`     — computed at FastAPI startup by the boot-fitted
                     `LagLinearForecaster` on the same 14-day
                     held-out window.

    """

    notebook = "notebook"
    live = "live"


class LeaderboardRow(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    model_name: str = Field(
        ...,
        alias="modelName",
        description="Display name. Notebook rows preserve their printed labels\n(e.g. `Naive (last value)`, `Holt-Winters (add, m=24)`,\n`SARIMA(1,0,1)(1,0,1,24)`); the live row carries the\nforecaster's `model_version` (e.g. `lag-lr-v1`).\n",
    )
    mae: float = Field(
        ..., description="Mean absolute error on the 14-day held-out window.", ge=0.0
    )
    rmse: float = Field(
        ...,
        description="Root mean squared error on the 14-day held-out window.",
        ge=0.0,
    )
    mape: float | None = Field(
        None,
        description="Mean absolute percentage error. `null` for rows whose\nsource did not report MAPE.\n",
    )
    smape: float | None = Field(
        None,
        description="Symmetric mean absolute percentage error. `null` for rows\nwhose source did not report sMAPE.\n",
    )
    provenance: Provenance
    evaluated_at: AwareDatetime = Field(
        ...,
        alias="evaluatedAt",
        description="UTC timestamp at which the row was persisted. Notebook rows\ncarry the seeder run-time (re-MERGE refreshes it); the live\nrow carries the boot-fit completion time.\n",
    )


class LeaderboardResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    rows: list[LeaderboardRow] = Field(
        ...,
        description="All rows in `dbo.Leaderboard`, ordered by `mae` ascending.\nEmpty during the brief lifespan window before\n`LeaderboardSeeder` completes.\n",
    )
