-- =====================================================================
-- ClimaSense — canonical schema (Slice 1: Foundation).
--
-- This script is the SQL-first schema authority. It is:
--
--   * Idempotent. Re-running on an existing database is a no-op for every
--     object; CREATE...IF NOT EXISTS is emulated via metadata guards
--     because SQL Server lacks a true `CREATE TABLE IF NOT EXISTS`.
--
--   * Empty-by-design at slice 1. No data is inserted here other than
--     three seed alert rules that live alongside their schema. CSV
--     ingestion lands in slice 3 (#5) via `bcp`.
--
--   * The single source of truth. EF Core scaffolds POCOs from this DB
--     (Database-First); SQLAlchemy reflects via `autoload_with=engine`.
--     There is NO migration tool.
--
-- Provenance:
--   Numeric constants in the `Pattern` CASE expression and threshold
--   alert seeds carry inline comments citing the notebook source. When
--   a specific cell could not be identified the citation reads
--   "from notebook EDA section §X" instead — see the slice-1 PR's
--   "Judgment calls" for unresolved citations.
-- =====================================================================

SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;

-- ---------------------------------------------------------------------
-- 1. Database
-- ---------------------------------------------------------------------
IF DB_ID(N'ClimaSense') IS NULL
BEGIN
    CREATE DATABASE [ClimaSense];
END;
GO

USE [ClimaSense];
GO

-- ---------------------------------------------------------------------
-- 2. Tables
-- ---------------------------------------------------------------------

-- 2.1 SensorReadings — the raw mirrored stream.
--
--     PK is non-clustered on `Id` so the table can be physically
--     ordered by `ReadingTime` for sequential time-series scans.
IF OBJECT_ID(N'dbo.SensorReadings', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.SensorReadings
    (
        Id          BIGINT IDENTITY(1,1) NOT NULL,
        ReadingTime DATETIME2(3) NOT NULL,
        Temperature DECIMAL(6, 3) NOT NULL,
        Humidity    DECIMAL(6, 3) NOT NULL,
        CONSTRAINT PK_SensorReadings PRIMARY KEY NONCLUSTERED (Id)
    );

    CREATE CLUSTERED INDEX IX_SensorReadings_ReadingTime
        ON dbo.SensorReadings (ReadingTime);

    CREATE NONCLUSTERED INDEX IX_SensorReadings_Temperature
        ON dbo.SensorReadings (Temperature);

    CREATE NONCLUSTERED INDEX IX_SensorReadings_Humidity
        ON dbo.SensorReadings (Humidity);
END;
GO

-- 2.2 Anomalies — typed events from the three-detector pipeline.
--
--     UNIQUE(AnomalyType, ReadingTime) makes per-type idempotency a
--     schema property, not caller discipline.
IF OBJECT_ID(N'dbo.Anomalies', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Anomalies
    (
        AnomalyId   BIGINT IDENTITY(1,1) NOT NULL,
        ReadingTime DATETIME2(3) NOT NULL,
        AnomalyType VARCHAR(32) NOT NULL,
        Severity    DECIMAL(8, 4) NOT NULL,
        Score       DECIMAL(8, 4) NULL,
        Description NVARCHAR(512) NULL,
        DetectedAt  DATETIME2(3) NOT NULL CONSTRAINT DF_Anomalies_DetectedAt DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_Anomalies PRIMARY KEY CLUSTERED (AnomalyId),
        CONSTRAINT UQ_Anomalies_TypeTime UNIQUE (AnomalyType, ReadingTime),
        CONSTRAINT CK_Anomalies_Type CHECK
            (AnomalyType IN (N'sensor_failure', N'regime_shift', N'residual_outlier'))
    );

    CREATE NONCLUSTERED INDEX IX_Anomalies_ReadingTime ON dbo.Anomalies (ReadingTime);
    CREATE NONCLUSTERED INDEX IX_Anomalies_DetectedAt  ON dbo.Anomalies (DetectedAt);
END;
GO

-- 2.3 Forecasts — generated by `LagLinearForecaster` (and possibly future
--     siblings). `ModelVersion` records the producing implementation.
--
--     Read queries clip with `WHERE GeneratedAt <= @asOf` so forecasts
--     produced at any cursor position remain correct historical artefacts.
IF OBJECT_ID(N'dbo.Forecasts', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Forecasts
    (
        ForecastId           BIGINT IDENTITY(1,1) NOT NULL,
        GeneratedAt          DATETIME2(3) NOT NULL,
        TargetTime           DATETIME2(3) NOT NULL,
        PredictedTemperature DECIMAL(7, 3) NOT NULL,
        PredictedHumidity    DECIMAL(7, 3) NOT NULL,
        ConfidenceLowerTemp  DECIMAL(7, 3) NULL,
        ConfidenceUpperTemp  DECIMAL(7, 3) NULL,
        ModelVersion         VARCHAR(64) NOT NULL,
        CONSTRAINT PK_Forecasts PRIMARY KEY CLUSTERED (ForecastId)
    );

    CREATE NONCLUSTERED INDEX IX_Forecasts_GeneratedAt
        ON dbo.Forecasts (GeneratedAt) INCLUDE (TargetTime);

    CREATE NONCLUSTERED INDEX IX_Forecasts_TargetTime
        ON dbo.Forecasts (TargetTime);
END;
GO

-- 2.4 DayProfiles — calendar-conditioned z-scores; one row per (Date).
IF OBJECT_ID(N'dbo.DayProfiles', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.DayProfiles
    (
        DayProfileId   BIGINT IDENTITY(1,1) NOT NULL,
        [Date]         DATE NOT NULL,
        DayOfWeek      TINYINT NOT NULL,
        MeanResidual   DECIMAL(8, 4) NOT NULL,
        MaxAbsZscore   DECIMAL(8, 4) NOT NULL,
        Pattern        VARCHAR(16) NOT NULL,
        ComputedAt     DATETIME2(3) NOT NULL CONSTRAINT DF_DayProfiles_ComputedAt DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_DayProfiles PRIMARY KEY CLUSTERED (DayProfileId),
        CONSTRAINT UQ_DayProfiles_Date UNIQUE ([Date]),
        CONSTRAINT CK_DayProfiles_Pattern CHECK
            (Pattern IN (N'quiet', N'warm', N'cool', N'volatile')),
        CONSTRAINT CK_DayProfiles_DayOfWeek CHECK (DayOfWeek BETWEEN 0 AND 6)
    );
END;
GO

-- 2.5 ComfortScores — ASHRAE 55 graphical comfort zone evaluation per bucket.
IF OBJECT_ID(N'dbo.ComfortScores', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ComfortScores
    (
        ComfortScoreId BIGINT IDENTITY(1,1) NOT NULL,
        BucketTime     DATETIME2(3) NOT NULL,
        Score          DECIMAL(5, 2) NOT NULL,
        Rating         VARCHAR(16) NOT NULL,
        Season         VARCHAR(8) NOT NULL,
        ComputedAt     DATETIME2(3) NOT NULL CONSTRAINT DF_ComfortScores_ComputedAt DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_ComfortScores PRIMARY KEY CLUSTERED (ComfortScoreId),
        CONSTRAINT UQ_ComfortScores_Bucket UNIQUE (BucketTime),
        CONSTRAINT CK_ComfortScores_Rating CHECK
            (Rating IN (N'excellent', N'acceptable', N'marginal', N'uncomfortable')),
        CONSTRAINT CK_ComfortScores_Season CHECK (Season IN (N'summer', N'winter')),
        CONSTRAINT CK_ComfortScores_Score CHECK (Score BETWEEN 0 AND 100)
    );
END;
GO

-- 2.6 AlertRules — human-defined threshold rules. Seeded with three defaults.
IF OBJECT_ID(N'dbo.AlertRules', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.AlertRules
    (
        RuleId          INT IDENTITY(1,1) NOT NULL,
        Name            NVARCHAR(128) NOT NULL,
        Metric          VARCHAR(16) NOT NULL,
        Operator        VARCHAR(2) NOT NULL,
        Threshold       DECIMAL(7, 3) NOT NULL,
        DurationMinutes INT NOT NULL,
        Enabled         BIT NOT NULL CONSTRAINT DF_AlertRules_Enabled DEFAULT (1),
        CreatedAt       DATETIME2(3) NOT NULL CONSTRAINT DF_AlertRules_CreatedAt DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_AlertRules PRIMARY KEY CLUSTERED (RuleId),
        CONSTRAINT UQ_AlertRules_Name UNIQUE (Name),
        CONSTRAINT CK_AlertRules_Metric CHECK (Metric IN (N'T', N'RH')),
        CONSTRAINT CK_AlertRules_Operator CHECK (Operator IN (N'>', N'<')),
        CONSTRAINT CK_AlertRules_Duration CHECK (DurationMinutes > 0)
    );
END;
GO

-- 2.7 Alerts — closed breach intervals; append-only.
IF OBJECT_ID(N'dbo.Alerts', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Alerts
    (
        AlertId           BIGINT IDENTITY(1,1) NOT NULL,
        RuleId            INT NOT NULL,
        BreachStart       DATETIME2(3) NOT NULL,
        BreachEnd         DATETIME2(3) NOT NULL,
        PeakValue         DECIMAL(7, 3) NOT NULL,
        ReplayClockAtFire DATETIME2(3) NOT NULL,
        CONSTRAINT PK_Alerts PRIMARY KEY CLUSTERED (AlertId),
        CONSTRAINT UQ_Alerts_RuleStart UNIQUE (RuleId, BreachStart),
        CONSTRAINT FK_Alerts_AlertRules FOREIGN KEY (RuleId)
            REFERENCES dbo.AlertRules (RuleId)
    );

    CREATE NONCLUSTERED INDEX IX_Alerts_ReplayClockAtFire
        ON dbo.Alerts (ReplayClockAtFire);
END;
GO

-- 2.8 Leaderboard — heterogeneous: notebook rows + one live row.
--
--     `Provenance` distinguishes the two origins (CONTEXT.md → "Provenance").
IF OBJECT_ID(N'dbo.Leaderboard', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Leaderboard
    (
        LeaderboardId BIGINT IDENTITY(1,1) NOT NULL,
        ModelName     VARCHAR(64) NOT NULL,
        Mae           DECIMAL(8, 4) NOT NULL,
        Rmse          DECIMAL(8, 4) NOT NULL,
        Mape          DECIMAL(8, 4) NULL,
        Smape         DECIMAL(8, 4) NULL,
        Provenance    VARCHAR(16) NOT NULL,
        EvaluatedAt   DATETIME2(3) NOT NULL CONSTRAINT DF_Leaderboard_EvaluatedAt DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_Leaderboard PRIMARY KEY CLUSTERED (LeaderboardId),
        CONSTRAINT UQ_Leaderboard_Model UNIQUE (ModelName),
        CONSTRAINT CK_Leaderboard_Provenance CHECK (Provenance IN (N'notebook', N'live')),
        -- Bounds derived from results.json `forecast_results` and `sequence_results`
        -- blocks of Climate_Time_Series_Analysis.ipynb (see notebook §7.9 and §8.5.8):
        --   MAE  observed range: 0.214 .. 0.571
        --   RMSE observed range: 0.293 .. 0.649
        -- Wide guard rails accommodate future live rows and notebook re-runs.
        CONSTRAINT CK_Leaderboard_NonNeg CHECK (Mae >= 0 AND Rmse >= 0)
    );
END;
GO

-- ---------------------------------------------------------------------
-- 3. Inline table-valued functions — cursor-clipped views per CONTEXT.md
--    The `clip()` operation on `CursorSnapshot` covers raw `SensorReadings`;
--    derived tables clip via these schema-level functions so cursor
--    discipline is structural rather than caller-driven.
-- ---------------------------------------------------------------------

-- 3.1 Forecasts — clip on GeneratedAt (the production-time of the row).
IF OBJECT_ID(N'dbo.fv_forecasts_at_cursor', N'IF') IS NOT NULL
    DROP FUNCTION dbo.fv_forecasts_at_cursor;
GO
CREATE FUNCTION dbo.fv_forecasts_at_cursor (@asOf DATETIME2(3))
RETURNS TABLE
AS
RETURN
(
    SELECT  ForecastId,
            GeneratedAt,
            TargetTime,
            PredictedTemperature,
            PredictedHumidity,
            ConfidenceLowerTemp,
            ConfidenceUpperTemp,
            ModelVersion
    FROM    dbo.Forecasts
    WHERE   GeneratedAt <= @asOf
);
GO

-- 3.2 Anomalies — clip on DetectedAt (when the detector saw it). Reading-time
--     remains the event timestamp; cursor governs visibility of the detection.
IF OBJECT_ID(N'dbo.fv_anomalies_at_cursor', N'IF') IS NOT NULL
    DROP FUNCTION dbo.fv_anomalies_at_cursor;
GO
CREATE FUNCTION dbo.fv_anomalies_at_cursor (@asOf DATETIME2(3))
RETURNS TABLE
AS
RETURN
(
    SELECT  AnomalyId,
            ReadingTime,
            AnomalyType,
            Severity,
            Score,
            Description,
            DetectedAt
    FROM    dbo.Anomalies
    WHERE   DetectedAt <= @asOf
);
GO

-- 3.3 DayProfiles — clip on the profile date itself: a profile for date D is
--     visible iff the cursor has reached D (00:00 of D+1 as upper bound).
IF OBJECT_ID(N'dbo.fv_dayprofiles_at_cursor', N'IF') IS NOT NULL
    DROP FUNCTION dbo.fv_dayprofiles_at_cursor;
GO
CREATE FUNCTION dbo.fv_dayprofiles_at_cursor (@asOf DATETIME2(3))
RETURNS TABLE
AS
RETURN
(
    SELECT  DayProfileId,
            [Date],
            DayOfWeek,
            MeanResidual,
            MaxAbsZscore,
            Pattern,
            ComputedAt
    FROM    dbo.DayProfiles
    WHERE   ComputedAt <= @asOf
);
GO

-- 3.4 ComfortScores — clip on BucketTime (the moment the score is *for*).
IF OBJECT_ID(N'dbo.fv_comfortscores_at_cursor', N'IF') IS NOT NULL
    DROP FUNCTION dbo.fv_comfortscores_at_cursor;
GO
CREATE FUNCTION dbo.fv_comfortscores_at_cursor (@asOf DATETIME2(3))
RETURNS TABLE
AS
RETURN
(
    SELECT  ComfortScoreId,
            BucketTime,
            Score,
            Rating,
            Season,
            ComputedAt
    FROM    dbo.ComfortScores
    WHERE   BucketTime <= @asOf
);
GO

-- 3.5 Alerts — clip on ReplayClockAtFire (the explicit clock provenance).
IF OBJECT_ID(N'dbo.fv_alerts_at_cursor', N'IF') IS NOT NULL
    DROP FUNCTION dbo.fv_alerts_at_cursor;
GO
CREATE FUNCTION dbo.fv_alerts_at_cursor (@asOf DATETIME2(3))
RETURNS TABLE
AS
RETURN
(
    SELECT  AlertId,
            RuleId,
            BreachStart,
            BreachEnd,
            PeakValue,
            ReplayClockAtFire
    FROM    dbo.Alerts
    WHERE   ReplayClockAtFire <= @asOf
);
GO

-- ---------------------------------------------------------------------
-- 4. Pattern thresholds for `DayProfiles.Pattern`.
--
--    Encoded as a SQL inline TVF so the recompute job can `INSERT INTO
--    DayProfiles SELECT ... FROM dbo.fn_classify_pattern(MeanResidual,
--    MaxAbsZscore)`.
--
--    Provenance — EMPIRICAL (slice 9). These three constants are
--    produced by `scripts/derive_pattern_thresholds.py` running against
--    the full `sensor_data.csv` (after the same hourly-resample +
--    linear-interpolation pipeline the forecaster uses). The script is
--    deterministic; rerunning it yields identical numbers. The
--    derivation methodology (and the receipts) live in
--    `SLICE-9-NOTES.md` plus the script's own module docstring.
--
--    Training window: 2016-01-20 -> 2026-05-07
--    Hourly rows in scope: 90,239
--    Daily profiles aggregated: 3,754
--
--      * `volatile` — MaxAbsZscore > 3.059456  (p90 of MaxAbsZscore over
--        the per-day population)
--      * `warm`     — MeanResidual >  0.027845 (p75 of MeanResidual)
--      * `cool`     — MeanResidual < -0.024658 (p25 of MeanResidual)
--      * `quiet`    — otherwise
--
--    Precedence: volatile > warm > cool > quiet.
--
--    Slice 1 shipped standard-normal placeholders (1.281552, ±0.6745)
--    with a TODO(slice-9) marker; this slice replaces them with the
--    empirical numbers above. To re-derive after the data accumulates:
--        python3 scripts/derive_pattern_thresholds.py
--    and paste the resulting CASE expression below.
-- ---------------------------------------------------------------------

IF OBJECT_ID(N'dbo.fn_classify_pattern', N'IF') IS NOT NULL
    DROP FUNCTION dbo.fn_classify_pattern;
GO
CREATE FUNCTION dbo.fn_classify_pattern
(
    @meanResidual  DECIMAL(8, 4),
    @maxAbsZscore  DECIMAL(8, 4)
)
RETURNS TABLE
AS
RETURN
(
    SELECT
        CAST(
            CASE
                -- volatile wins when the day's worst |z| exceeds p90.
                -- 3.059456 = p90(MaxAbsZscore) across the full
                -- training-window population (slice-9 derivation).
                WHEN @maxAbsZscore > 3.059456 THEN N'volatile'
                -- warm / cool driven by the day's mean residual against
                -- its calendar cohort.
                -- p75(MeanResidual) =  0.027845, p25(MeanResidual) = -0.024658
                -- (slice-9 derivation).
                WHEN @meanResidual >  0.027845 THEN N'warm'
                WHEN @meanResidual < -0.024658 THEN N'cool'
                ELSE N'quiet'
            END
            AS VARCHAR(16)
        ) AS Pattern
);
GO

-- ---------------------------------------------------------------------
-- 5. Seed rows
--
-- Three default alert rules. Defaults are deliberately conservative;
-- the operator can override via slice-11 CRUD UI (deferred per ADR-0011).
--
-- Provenance: the three rule shapes come directly from PRD #2's
--   "Alerts and SSE" section ("e.g. T > 26 °C for 30 min, RH > 70 %
--   for 60 min, T < 18 °C for 60 min"). The numeric values themselves
--   are operator-comfort defaults, not notebook-derived.
-- ---------------------------------------------------------------------
MERGE dbo.AlertRules AS target
USING (VALUES
    -- (Name, Metric, Operator, Threshold, DurationMinutes)
    (N'Heat: T > 26 °C sustained 30 min', N'T',  N'>', CAST(26.000 AS DECIMAL(7, 3)), 30),
    (N'Cold: T < 18 °C sustained 60 min', N'T',  N'<', CAST(18.000 AS DECIMAL(7, 3)), 60),
    (N'Damp: RH > 70 % sustained 60 min', N'RH', N'>', CAST(70.000 AS DECIMAL(7, 3)), 60)
) AS src (Name, Metric, Operator, Threshold, DurationMinutes)
ON target.Name = src.Name
WHEN NOT MATCHED THEN
    INSERT (Name, Metric, Operator, Threshold, DurationMinutes, Enabled)
    VALUES (src.Name, src.Metric, src.Operator, src.Threshold, src.DurationMinutes, 1);
GO

-- ---------------------------------------------------------------------
-- 6. End marker
-- ---------------------------------------------------------------------
PRINT N'init-db.sql applied: schema is current.';
GO
