#!/usr/bin/env bash
# ----------------------------------------------------------------------
# regen-contracts.sh
#
# Single source of truth: contracts/openapi.yaml.
# This script regenerates the .NET and Python codegen outputs against it.
#
# Idempotent — re-running on already-generated code produces zero diff.
#
# Tools used:
#   * .NET    — Microsoft.OpenApi.Kiota (dotnet local tool).
#   * Python  — datamodel-code-generator (uv dev dependency).
#
# Failure modes:
#   * If Kiota is missing locally: emit an actionable install message
#     and exit 1.
#   * If datamodel-code-generator is missing: emit an actionable
#     install message and exit 1.
#
# Usage:
#   bash scripts/regen-contracts.sh        # regenerate both
#   bash scripts/regen-contracts.sh dotnet # regenerate .NET only
#   bash scripts/regen-contracts.sh python # regenerate Python only
# ----------------------------------------------------------------------

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONTRACT="$ROOT/contracts/openapi.yaml"
WHICH="${1:-all}"

if [ ! -f "$CONTRACT" ]; then
  echo "regen-contracts: $CONTRACT not found" >&2
  exit 1
fi

regen_python() {
  echo "==> Python: regenerating Pydantic models from $CONTRACT"

  local OUT="$ROOT/src/ClimaSense.ML/climasense_ml/schemas/generated.py"
  mkdir -p "$(dirname "$OUT")"

  # Resolve datamodel-codegen.
  # Prefer the project's uv-managed venv if it exists; fall back to the
  # ambient `datamodel-codegen` on PATH; finally try `python3 -m`.
  local CODEGEN=""
  if command -v datamodel-codegen >/dev/null 2>&1; then
    CODEGEN="datamodel-codegen"
  elif python3 -c "import datamodel_code_generator" >/dev/null 2>&1; then
    CODEGEN="python3 -m datamodel_code_generator"
  else
    cat >&2 <<'EOF'
regen-contracts: datamodel-code-generator not found.

Install one of:
  uv sync --extra dev                  # inside src/ClimaSense.ML/
  pipx install datamodel-code-generator
  pip install datamodel-code-generator
EOF
    exit 1
  fi

  # `--snake-case-field` produces python-idiomatic field names.
  # `--field-constraints` keeps min/max constraints on the Pydantic side
  # (so 501-stub callers can't smuggle out-of-range integers).
  # `--use-schema-description` puts component descriptions into docstrings
  # for IDE hover support.
  # `--output-model-type pydantic_v2.BaseModel` pins us to Pydantic v2.
  # `--use-double-quotes` keeps the output stable across re-runs.
  # `--target-python-version 3.13` matches the project's `requires-python`.
  $CODEGEN \
    --input "$CONTRACT" \
    --input-file-type openapi \
    --output "$OUT" \
    --output-model-type pydantic_v2.BaseModel \
    --use-schema-description \
    --use-double-quotes \
    --snake-case-field \
    --field-constraints \
    --target-python-version 3.13 \
    --disable-timestamp \
    --use-standard-collections \
    --use-union-operator \
    --enable-version-header

  # Append a stable comment block so the file always carries an explicit
  # "do not edit — regenerated" preamble. Prepend it instead.
  python3 - "$OUT" <<'PYEOF'
import pathlib, sys
p = pathlib.Path(sys.argv[1])
body = p.read_text()
banner = (
    "# === GENERATED — DO NOT EDIT BY HAND ===\n"
    "# Regenerated by scripts/regen-contracts.sh from contracts/openapi.yaml.\n"
    "# Pydantic v2 models. camelCase JSON aliases on the wire are produced\n"
    "# by datamodel-code-generator's `--snake-case-field` mode plus the\n"
    "# emitted `Field(..., alias=\"camelCase\")` annotations.\n"
    "\n"
)
if not body.startswith("# === GENERATED"):
    p.write_text(banner + body)
PYEOF

  echo "    wrote $OUT"
}

regen_dotnet() {
  echo "==> .NET: regenerating Kiota client from $CONTRACT"

  local OUT_DIR="$ROOT/src/ClimaSense.Web/Generated/MLClient"
  mkdir -p "$OUT_DIR"

  # Resolve `kiota`. We use the project's local tool manifest at
  # `.config/dotnet-tools.json`; `dotnet tool restore` is idempotent.
  pushd "$ROOT" >/dev/null

  if ! command -v dotnet >/dev/null 2>&1; then
    echo "regen-contracts: dotnet SDK not found on PATH" >&2
    popd >/dev/null
    exit 1
  fi

  if ! dotnet kiota --version >/dev/null 2>&1; then
    echo "    Kiota not restored yet — running 'dotnet tool restore'"
    if ! dotnet tool restore >/dev/null 2>&1; then
      cat >&2 <<'EOF'
regen-contracts: `dotnet tool restore` failed.

Install Kiota globally as a fallback:
  dotnet tool install --global Microsoft.OpenApi.Kiota
EOF
      popd >/dev/null
      exit 1
    fi
  fi

  # Preserve hand-written companion files (the README explaining what
  # this directory is). Stash before the wipe; restore after.
  local KEEP_README="$OUT_DIR/README.md"
  local STASH_README=""
  if [ -f "$KEEP_README" ]; then
    STASH_README="$(mktemp -t climasense-kiota-readme.XXXXXX)"
    cp "$KEEP_README" "$STASH_README"
  fi

  # Wipe the generated tree before regenerating so deleted endpoints
  # don't leave orphans behind. `--clean-output` on `dotnet kiota` does
  # this too, but doing it explicitly keeps the script self-contained.
  if [ -d "$OUT_DIR" ]; then
    find "$OUT_DIR" -mindepth 1 -delete
  fi

  dotnet kiota generate \
    --openapi "$CONTRACT" \
    --language CSharp \
    --output "$OUT_DIR" \
    --namespace-name ClimaSense.Web.Generated.MLClient \
    --class-name MLApiClient \
    --clean-output \
    --clear-cache \
    --exclude-backward-compatible \
    --log-level Warning

  # Restore the README so reviewers see context next to the generated tree.
  if [ -n "$STASH_README" ] && [ -f "$STASH_README" ]; then
    cp "$STASH_README" "$KEEP_README"
    rm "$STASH_README"
  fi

  popd >/dev/null
  echo "    wrote $OUT_DIR"
}

case "$WHICH" in
  all)
    regen_python
    regen_dotnet
    ;;
  python|py)
    regen_python
    ;;
  dotnet|cs|csharp)
    regen_dotnet
    ;;
  *)
    echo "usage: $0 [all|python|dotnet]" >&2
    exit 2
    ;;
esac

echo "regen-contracts: done."
